require(tseries) 
setwd("D:/")
d=read.csv("maharain.csv")
rain_ts <- ts(d[,3], frequency =12, start = 1901)
class(rain_ts)
start(rain_ts)
end(rain_ts)
plot(rain_ts)
rain.hw <- HoltWinters(rain_ts, seasonal="additive")
rain.predict<-predict(rain.hw, n.ahead=10*2)
ts.plot(rain_ts, rain.predict, lty=1:2)
